version: "3"
services:
  web:
    build: .
    command: yarn start
    container_name: frontend_web
    environment:
      BASE_URL: "http://backend_web_1:8000/"
    networks:
      - default
      - shared-network
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
networks:
  shared-network:
    external: true
volumes:
  node_modules:

